import EventList from "@/components/events/EventList";
import { getFeaturedEvents } from "@/dummy-data";
import Head from "next/head";

export default function Home() {
  const featuredEvents = getFeaturedEvents();
  return (
    <>
      <Head>
        <title>Next.js Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <EventList events={featuredEvents} />
      </main>
    </>
  );
}
