import EventList from "@/components/events/EventList";
import { getFeaturedEvents } from "@/helpers/api-utils";
import { EventType } from "@/types/event";
import { GetStaticProps, InferGetStaticPropsType } from "next";
import Head from "next/head";

export default function Home({
  events,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <>
      <Head>
        <title>Next.js Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <EventList events={events} />
      </main>
    </>
  );
}

// Incremental Static Regeneration (ISR):
export const getStaticProps: GetStaticProps<{
  events: EventType[];
}> = async () => {
  const featuredEvents = await getFeaturedEvents();
  return {
    props: {
      events: featuredEvents,
    },
    // everry 30 minutes the page will be re-generated
    revalidate: 1800,
  };
};
